/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.cooper.moviemadness;

public final class R {
    public static final class array {
        public static final int search_kinds=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_icon=0x7f020000;
    }
    public static final class id {
        public static final int director=0x7f070008;
        public static final int field_label=0x7f070002;
        public static final int field_value=0x7f070003;
        public static final int movie_title=0x7f070007;
        public static final int prompt_label=0x7f070000;
        public static final int result_values=0x7f070006;
        public static final int search=0x7f070001;
        public static final int search_button=0x7f070004;
        public static final int section=0x7f070009;
        public static final int spinner_item=0x7f07000b;
        public static final int status_message=0x7f070005;
        public static final int year=0x7f07000a;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int row=0x7f030001;
        public static final int spinner_view=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f050003;
        public static final int field_label=0x7f050001;
        public static final int prompt_label=0x7f050000;
        public static final int search_button_label=0x7f050002;
        public static final int status_message=0x7f050004;
    }
    public static final class style {
        public static final int spinner_item=0x7f060000;
        public static final int spinner_item_dropdown=0x7f060001;
    }
}
